version: "3.8"
services:
  web-app:
    image: "ntloc/course-enrollment-management-application:latest"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev